[package]
name = "nugget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", features = ["webgl"] }
env_logger = "0.9.0"
pollster = "0.2.5"
winit = "0.26.1"
